### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by vietj** [aesteve/vertx-aws-sdk#1]
it would be great to have Travis integration for PR's

**Comment by vietj** [comment]
preums issue!

**Comment by aesteve** [comment]
https://travis-ci.org/aesteve/vertx-aws-sdk

The `AsyncHttpClientTest` are failing only on travis. They run fine locally.
```
    io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8000
```
